### ISSUE TITLE
Inclusão de arquivo no FTP das PNADs causando problemas na função getpnadc

### ISSUE THREAD

**Issue by romulo-drl** [cran/PNADcIBGE#3]
Bom dia pessoal, tudo jóia? Verifiquei que ontem (24/02) foram inseridos alguns zips no FTP que impedem o funcionamento do getpnadc, trigando a mensagem de duplicação:

"There is more than one file available for the requested microdata, please contact the package maintainer."

Acredito que uma atualização possa ser necessária.

https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2021/

Abraços!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Gabriel-Assuncao** [comment]
Prezado Romulo, boa tarde.

Agradecemos imensamente pela indicação do problema, já estamos entrando em contato com a área responsável para resolução da situação.

Aproveitamos para indicar que sempre que forem identificados problemas ou se surgirem dúvidas com relação à utilização do pacote, para que entre em contato com o canal de atendimento pacotesipd@ibge.gov.br.

Sendo assim, agradecemos imensamente pela atenção e estamos à disposição para qualquer eventualidade.

**Comment by Gabriel-Assuncao** [comment]
Prezado Romulo, boa tarde.

Informamos que o problema já foi corrigido, então a utilização do pacote para obtenção e leitura dos microdados trimestrais da PNAD Contínua voltou a funcionar corretamente.

Pedimos por gentileza o fechamento desta _issue_ e solicitamos que sempre que for necessário, entrar em contato através do canal de atendimento pacotesipd@ibge.gov.br.

Sendo assim, agradecemos imensamente pela atenção e estamos à disposição para qualquer eventualidade.
