### ISSUE TITLE
Problema ao importar a PNAD Contínua 2019 para o tema de turismo

### ISSUE THREAD

**Issue by Emmanuel1524** [cran/PNADcIBGE#5]
Boa noite Gabriel, como vai?

Estou tentando importar os dados da PNAD 2019 para o tópico especial de turismo, mas quando executo o seguinte código, uma mensagem de erro é retornada:

`dadosPNADc_anual_trimestre <- get_pnadc(year = 2019, topic = 3)`

**error message**

"tentando a URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_3/Documentacao/.xls'
Error in utils::download.file(url = paste0(ftpdir, "Trimestre_", defperiod,  : 
  não foi possível abrir a URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_3/Documentacao/.xls' "

Investigando o erro e replicando o request da URL que você programou, percebi que o arquivo que a função deveria pegar já não se encontra mais no diretório explicitado. Caminhando na URL do site vi que existe outra pasta chamada "Dados" onde supostamente a base da PNAD do terceiro semestre para turismo está contida....

É uma falha minha ou realmente os arquivos que a URL está procurando foram movidos?

Muito obrigado e forte abraço!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Gabriel-Assuncao** [comment]
Prezado Emmanuel, bom dia.
Verifiquei no arquivos de referência de deflatores no servidor e de fato por algum motivo o deflator do ano de 2019 foi removido indevidamente, já comuniquei à equipe responsável que em breve deverá efetuar a correção e disponibilizar o arquivo necessário em tal diretório. Caso queira utilizar a função sem que ocorra o erro provisoriamente, é possível indicar o argumento deflator=FALSE ou fornecer os valores para os argumentos defyear=2021 e defperiod=3 dentro da função get_pnadc do pacote PNADcIBGE, que daí a rotina funcionará perfeitamente.
Aproveito para solicitar o fechamento desta issue e caso surjam novas dúvidas ou problemas peço por gentileza que faça a abertura da issue em https://github.com/Gabriel-Assuncao/PNADcIBGE/issues ou envie um e-mail para o canal de atendimento pacotesipd@ibge.gov.br.
Agradeço imensamente pela atenção e me coloco à disposição para qualquer eventualidade.

--------------------------------------------------------------------------------------------------------------------------

Dear Emmanuel, good morning.
I checked the deflator reference files on the server and in fact for some reason the 2019 deflator was improperly removed, I have already communicated to the responsible team that they will soon make the correction and make the necessary file available in that directory. If you want to use the function without the error occurring temporarily, you can indicate the argument deflator=FALSE or provide the values ​​for the arguments defyear=2021 and defperiod=3 within the get_pnadc function of the PNADcIBGE package, and then the routine will work perfectly.
I would like to take the opportunity to request the closing of this issue and if new questions or problems arise, I kindly ask you to open the issue at https://github.com/Gabriel-Assuncao/PNADcIBGE/issues or send an email to the service channel pacotesipd@ibge.gov.br.
I thank you immensely for your attention and I make myself available for any eventuality.
