### ISSUE TITLE
Problemas para importação de dados

### ISSUE THREAD

**Issue by ulisses-csf** [cran/PNADcIBGE#6]
Olá, boa tarde!
Eu comumente utilizo o pacote para fazer leitura da PNADc. No entanto, dessa vez apareceu um erro que eu nunca tinha visto e não tenho ideia de como resolver.

A mensagem de erro é a seguinte:
Error in svrepdesign.default(data = data_pnadc, weight = ~V1032, type = "bootstrap",  : 
  Missing values not allowed in 'repweights'

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Gabriel-Assuncao** [comment]
Prezado Ulisses, boa tarde.

Por gentileza solicito o fechamento desta issue neste Git relacionado ao CRAN, pois esta página é apenas um espelho, irei lhe responder diretamente no Git dedicado em minha página, obrigado pela compreensão.

Dear Ulisses, good afternoon.

Please, I ask you to close this issue in this Git related to CRAN, as this page is just a mirror, I will answer you directly in the dedicated Git on my page, thank you for understanding.
