### ISSUE TITLE
Variáveis dos domicílios

### ISSUE THREAD

**Issue by ulisses-csf** [cran/PNADcIBGE#7]
Olá, com a função get_pnadc eu consigo trazer as variáveis dos domicílios? Eu só consigo ter acesso as informações das pessoas.

**Comment by Gabriel-Assuncao** [comment]
Prezado @ulisses-csf, bom dia.

Informo que os quesitos relacionados à divulgação de característica dos domicílios são coletadas através dos microdados anuais acumulados na 1ª visita de cada ano, assim para obter tal recorte basta utilizar a função _get_pnadc_ do pacote _PNADcIBGE_ inserindo o valor do ano desejado ao argumento _year_ e para o argumento _interview_ fornecer o valor de 1.

Assim, as informações de domicílios estarão disponíveis junto com as informações das pessoas, sendo que as pessoas que residem em um mesmo domicílio receberão as informações referentes ao domicílios de forma replicada, por isso que ao obter estimativas em nível de domicílio é necessário incluir um recorte com a função _subset_ no argumento _design_ na utilização das funções do pacote _survey_ para a variável V2005 recebendo o valor de 'Pessoa responsável pelo domicílio'.

Aproveito para solicitar o fechamento desta _issue_ e caso surjam novas dúvidas ou problemas peço por gentileza que faça a abertura da _issue_ em https://github.com/Gabriel-Assuncao/PNADcIBGE/issues ou envie um e-mail para o canal de atendimento [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br).

Agradeço imensamente pela atenção e me coloco à disposição para qualquer eventualidade.
________________________________________________________________________________________________________________________________

Dear @ulisses-csf, good morning.

I would like to inform you that the questions related to the disclosure of household characteristics are collected through annual microdata accumulated in the first visit of each year. To obtain this topic, simply use the _get_pnadc_ function from the _PNADcIBGE_ package, inserting the value of the desired year in the _year_ argument and providing the value of 1 in the _interview_ argument.

Therefore, household information will be available together with information about individuals, and individuals living in the same household will receive information about their households in a replicated way. This is why, when obtaining estimates at the household level, it is necessary to include a filter with the _subset_ function in the _design_ argument when using the functions of the _survey_ package for the variable V2005, receiving the value of 'Pessoa responsável pelo domicílio'.

I would like to take the opportunity to request the closing of this _issue_ and if new questions or problems arise, I kindly ask you to open the _issue_ at https://github.com/Gabriel-Assuncao/PNADcIBGE/issues or send an email to the service channel [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br).

I thank you immensely for your attention and I make myself available for any eventuality.
